### ISSUE TITLE
Trying to find an ex colleague 

### ISSUE THREAD

**Issue by uriencedric** [AlexJosse/incandescance-final#1]
Hello, I know that this might not be the place but, anyway.
I used to work with Jérôme Heitor, a while back in a company named Jumia, and I found his github. Do you have any news from him  ?
Best

**Comment by AlexJosse** [comment]
Hello,

I am really sorry for late answer I didn't see your email. Jerome is dead the 20 February 2020 in paris 🙁.
Are you french ? Where are you from and how did you meet him ?
I am sorry again for late answer and this terrible news. If you want to know more details contact by email : alexandre.josse@epitech.eu.
https://www.deces-en-france.fr/resultats/25017306-heitor-jerome
[https://www.deces-en-france.fr/images/deceased-man.jpg]<https://www.deces-en-france.fr/resultats/25017306-heitor-jerome>
M. HEITOR Jerome - Décès en France - Moteur de recherche des personnes décédées en France<https://www.deces-en-france.fr/resultats/25017306-heitor-jerome>
Informations relatives à M. HEITOR Jerome né le 10/02/1994 et décédé le 24/02/2020. Moteur de recherche pour la généalogie parmi plus de 26 millions de résultats.
www.deces-en-france.fr


________________________________
De : Chris C ***@***.***>
Envoyé : samedi 1 mai 2021 08:10
À : AlexJosse/incandescance-final ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [AlexJosse/incandescance-final] Trying to find an ex colleague (#1)


Hello, I know that this might not be the place but, anyway.
I used to work with Jérôme Heitor, a while back in a company named Jumia, and I found his github. Do you have any news from him ?
Best
